### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Hiekki4** [krakentom/GarminSpotifyRemoteController#1]
Is the android stuff required to use this?

**Comment by krakentom** [comment]
Hello. Yes, the Android application is required to use this functionality. The Garmin application sends commands such as "play/stop," "next song," "volume up," "volume down," and "add to library" to the phone and waits for a response. The phone sends information about the currently playing track back to the Garmin application. The Android app uses the Garmin Connect IQ SDK to communicate with the Garmin device and waits for commands from it. When a command is received, the app calls the appropriate function through the Spotify SDK to control Spotify.

**Comment by Hiekki4** [comment]
Okay, i really want to try this, but im unable to login to the Garmin SDK Manager, is this possible to be modify to use the phone midia player, and then there is no need to use the android app?

**Comment by krakentom** [comment]
I'm not sure if it will work, maybe it could be done through 
https://developer.garmin.com/connect-iq/api-docs/Toybox/Media/PlaybackProfile.html

I can give it a try. Initially, I thought this only works on devices with music storage support.

You'll still need the Garmin SDK Manager for developing applications for Garmin devices.

**Comment by Hiekki4** [comment]
I know i need it, but when i when i login, it shows the loading forever.

**Comment by Hiekki4** [comment]
What buttons are used to control the music?

**Comment by Hiekki4** [comment]
I think that if this works with the media player and not with the app, its better, i will try to change it.

**Comment by krakentom** [comment]
You need to press CTRL+SHIFT+P and type "Monkey C: Generate a Developer Key."

![image](https://github.com/krakentom/GarminSpotifyRemoteController/assets/30921208/15718e90-59e2-4fe8-aad3-468fc814bdf0)

**Comment by Hiekki4** [comment]
Okay, thanks

OBS: If you change the README.txt to README or README.md the # start working as headings.
