### ISSUE TITLE
Trouble Installing per instructions

### ISSUE THREAD

**Issue by ctferrarajr** [krakentom/GarminSpotifyRemoteController#2]
Let me preface by saying I'm not a developer and have already sunk about 2 hours into this. I'm computer literate but don't write apps. 

Here is where I'm at:

I was able to build and load the Garmin app. I have the app running on my 830. It shows a black screen and a hamburger menu with commands (next/play/pause/etc.). 

I was able to build and load the service. It shows a white full-screen app titled "Garmin Spotify Remote Control..." with a three-dot menu "Start Service/Stop Service". The rest of the page is white space. 

Tapping Start Service closes the app about half the time, with an error message that "Garmin Spotify Remote Controller" keeps stopping. This is running through developer mode, USB cable, initiated by the Android Studio app. 

I've created the Spotify App as specified, using the app package name and SH1 from the Android Studio. Is there anything else to do on this side? 

I am looking for some direction where I may have gone wrong.

I am surprised at the sparse information about this app; it seems as though this is a much-requested feature on the 830.

**Comment by ctferrarajr** [comment]
Another note: 

Step B5 tripped me up. I tried entering "edge830" as well as my Unit ID from my Garmin device (399####886). Neither of those allowed me to compile. I ended up generating a number from this site. Surely, this was not the right thing to do. If it matters I used the same number again in the Android App side of things. 

https://www.uuidgenerator.net/version1

**Comment by ctferrarajr** [comment]
I think I've overcome the B5 step, using the "Generate new UUID seemed to do it. Updated in the android app as well and still not crashing/not connecting.

**Comment by ctferrarajr** [comment]
Alright - Had a second breakthrough. This is now more just documentation for the next guy. There is a step missing in ReadMe. There should be a step after setting up your android app on spotify.com to copy your Client ID to the "MainActivity" file "Spotify Client ID" value. 

Should look something like this. 

    private val SPOTIFY_CLIENT_ID = "ccf3#########################89b"


This allowed the app to run correctly. 

Next/Play/Pause/Volume Up/Down/Like/Unlike are all working correctly. 

For some reason, it is not displaying the current track on the widget screen, though it is unclear exactly what the correct behavior of this is. 

Edit: after stopping and restarting the service the track/artist/length/and volume show up. 

I believe it is working 100% as intended now. Thank you for creating this app. Took me over 3 hours to get it going, but we made it, folks. This will save me dozens of seconds vs tapping my headphone skip button.

**Comment by krakentom** [comment]
Thx, readme was updated.
